name: ðŸŒŽ Web
on: [push, pull_request]

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-web
  cancel-in-progress: true

jobs:
  web:
    name: Web
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build-type:
          - Release
          #- Debug
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Cache
      #   id: cache-system-libraries
      #   uses: actions/cache@v2
      #   with:
      #     path: emsdk-cache
      #     key: emsdk-${{ runner.os }}

      - name: Emscripten
        uses: mymindstorm/setup-emsdk@v11
        with:
          #actions-cache-folder: 'emsdk-cache'
          no-cache: true
          version: 3.1.17

      - name: Verify Emscripten
        run: emcc -v

      - name: CMake
        run: emcmake script/cmake_emscripten.sh build -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} -DURHO3D_LIB_TYPE=static -DURHO3D_PROFILING=0

      - name: Build
        run: cmake --build build --parallel 2 --config ${{ matrix.build-type }}

      - name: Publish
        if: 0
        # TODO: port the ci_publish_web: task from the rakefile
